---
 - name: install apt-dater-host
   apt: pkg=apt-dater-host state=installed

 - name: apt-dater user
   user: system=true createhome=yes home="{{ apt_dater_host.home }}" name="{{ apt_dater_host.username }}" state=present shell=/bin/sh comment="Apt-dater user,,,"

 - name: ensure sudo installed
   apt: pkg=sudo state=installed

 - name: ensure .ssh dir
   file: state=directory path="{{ apt_dater_host.home }}/.ssh/" owner="{{ apt_dater_host.username }}" group=apt-dater mode=0700

 - name: install ssh-key
   authorized_key: key="{{ apt_dater_host.ssh_key }}" user="{{ apt_dater_host.username }}" state=present